FROM node:20
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 4200
# Usamos 0.0.0.0 para que sea accesible desde fuera del contenedor
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "4200"]